name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: collaborative_editor1
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" --health-interval=10s
          --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package -Dmaven.test.skip -e -X 

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: . 
          file: Dockerfile 
          push: true
          tags: ghassanyaseen/collaborative_editor:latest

      - name: Run Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 60  # Increased wait time

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test command here, e.g., curl, or a specific test script

      - name: Clean up
        run: |
          echo "Shutting down services..."
          docker-compose down

      - name: Show logs on failure
        if: failure()
        run: |
          echo "Displaying Docker logs..."
          docker-compose logs
